#   libzmq

language: c

os:
- linux
- osx

#   Build required projects first
before_script:

#   libsodium
#   Commit 8d0942 broke installation (sodium.h not found) so for now
#   we're checking out the last good commit.
- git clone git://github.com/jedisct1/libsodium.git
- cd libsodium
- git checkout e2a30a
- ./autogen.sh
- ./configure && make check
- sudo make install
- if [ $TRAVIS_OS_NAME != "osx" ] ; then sudo ldconfig ; fi
- cd ..

# ZMQ stress tests need more open socket (files) than the usual default
# On OSX, it seems the way to set the max files limit is constantly changing, so
# try to use all known knobs to ensure compatibility across various versions
- if [ $TRAVIS_OS_NAME == "osx" ] ; then sudo sysctl -w kern.maxfiles=64000 ; sudo sysctl -w kern.maxfilesperproc=64000 ; sudo launchctl limit maxfiles 64000 64000 ; fi ; ulimit -n 64000

#   Build and check libzmq
script: ./autogen.sh && ./configure && make V=1 && make check
